fix: Handle invalid input in TimeField and resolve missing CSS reference
webforj/webforj-docs-samples pull request #110
Opened 2024-11-29 02:58 UTC by laurenic0l

- Added input validation for TimeField to handle invalid time entries
- Updated `onModify` logic to validate and parse user input before setting the value.
- Disabled the confirm button for invalid inputs
- Removed missing CSS file reference (`timeFieldMinMaxView.css`)

closes #106

2024-11-29 07:05 UTC, hyyan requested changes

2024-11-29 07:05 UTC, hyyan commented on src/main/java/com/webforj/samples/views/fields/timefield/TimeFieldMinMaxView.java
> +    .onModify(e -> {
Use `onValueChange` and the get the value from the event's payload

2024-11-29 07:05 UTC, hyyan commented on src/main/java/com/webforj/samples/views/fields/timefield/TimeFieldMinMaxView.java
> +        App.console().log("Invalid time input: " + e.getText());
no browser console logs

2024-11-29 07:05 UTC, hyyan commented on src/main/java/com/webforj/samples/views/fields/timefield/TimeFieldMinMaxView.java
>  public class TimeFieldMinMaxView extends Composite<FlexLayout> {
Do something useful with the confirm button. A toast ?!

2024-12-02 15:51 UTC, laurenic0l commented on src/main/java/com/webforj/samples/views/fields/timefield/TimeFieldMinMaxView.java
>  public class TimeFieldMinMaxView extends Composite<FlexLayout> {
Implemented a toast to confirm the action

2024-12-02 15:51 UTC, laurenic0l commented on src/main/java/com/webforj/samples/views/fields/timefield/TimeFieldMinMaxView.java
> +        App.console().log("Invalid time input: " + e.getText());
Removed

2024-12-03 08:58 UTC, hyyan commented
https://github.com/webforj/webforj-docs/issues/353#issuecomment-2511915039

2024-12-03 08:58 UTC, closed without merging