Pull Request for Icon Component Demos
webforj/webforj-docs-samples pull request #70
Opened 2024-09-19 15:25 UTC by bbrennanbasis

- Added two demos using icons in a TabbedPane class
 - Added a folder in resources called icon to hold five custom icons

![custom-pool-icons](https://github.com/user-attachments/assets/b2e30a89-d08f-4640-a86b-f5501c8a13af)

2024-09-19 15:28 UTC, bbrennanbasis commented
@MatthewHawkins please review the demos I have currently and let me know what other demos need to be made for the Icon component.

2024-10-23 11:10 UTC, MatthewHawkins commented
@laurenic0l Which of these files do you have slated for use in the icon docs?

2024-10-28 09:03 UTC, MatthewHawkins submitted a review, later dismissed
These look good from a code/demo standpoint. 

@hyyan Do these fit more with what you're looking for? If so, which ones would you prefer to see on the doc site?

2024-10-28 11:03 UTC, hyyan commented on src/main/java/com/webforj/samples/views/icon/IconVariationsView.java
> +public class IconVariationsView extends Composite<FlexLayout> {
@laurenic0l this one is good, please include it please

2024-10-28 11:06 UTC, hyyan requested changes

2024-10-28 11:06 UTC, hyyan commented on src/main/java/com/webforj/samples/views/icon/IconPoolsView.java
> +public class IconPoolsView extends Composite<FlexLayout> {
@laurenic0l remove please

2024-10-28 11:06 UTC, hyyan commented on src/main/java/com/webforj/samples/views/icon/IconMenuView.java
> +public class IconMenuView extends Composite<Div> {
@laurenic0l remove please

2024-10-28 11:06 UTC, hyyan commented on src/main/java/com/webforj/samples/views/icon/IconItemCardView.java
> +public class IconItemCardView extends Composite<FlexLayout> {
@laurenic0l remove please

2024-10-28 11:06 UTC, hyyan commented on src/main/java/com/webforj/samples/views/icon/IconBasicsView.java
> +public class IconBasicsView extends Composite<FlexLayout> {
@laurenic0l this one is good, please include it but format the code first

2024-10-28 11:06 UTC, hyyan commented on src/main/java/com/webforj/samples/views/icon/IconActionButtonsView.java
> +public class IconActionButtonsView extends Composite<FlexLayout> {
@laurenic0l this one is good, please include it but format the code first

2024-10-30 14:29 UTC, hyyan commented on src/main/java/com/webforj/samples/views/icon/IconPrefixSuffixView.java
> +    .setTheme(ButtonTheme.SUCCESS);
change theme to primary please

2024-10-30 14:31 UTC, laurenic0l commented on src/main/resources/css/icon/iconItemCard.css
> +.item-card {
removed

2024-11-13 13:19 UTC, merged