PR - Demos for Spinner Loading Busy with Routing
webforj/webforj-docs-samples pull request #84
Opened 2024-10-09 13:33 UTC by laurenic0l

2024-10-10 08:43 UTC, hyyan requested changes

2024-10-10 08:43 UTC, hyyan commented on src/main/java/com/webforj/samples/views/loadingbusy/LoadingDemoView.java
> +  Icon guideIcon = TablerIcon.create("book");
Could we use different icons, please? Please take a look at the Feather icons.

2024-10-10 08:47 UTC, hyyan requested changes

2024-10-10 08:47 UTC, hyyan commented on src/main/java/com/webforj/samples/views/loadingbusy/BusySpinnerDemoView.java
> +public class BusySpinnerDemoView extends Composite<Div> {
This demo is similar to the one in `com.webforj.samples.views.busyindicator.BusyIndicatorView`. Please move the busy indicator sample there to keep things organized.

2024-10-10 08:48 UTC, hyyan commented
@laurenic0l Is the `SpinnerDemoView` currently in use? I kind of like that one. Can we change the spinner size to `XXXSMALL` and ensure all flex items are centered?

2024-10-10 08:56 UTC, hyyan commented on src/main/java/com/webforj/samples/views/loadingbusy/BusyDemoView.java
> +    formLayout.setJustifyContent(FlexJustifyContent.CENTER);
Use the FlexLayout builder to streamline layout creation.

2024-10-10 08:57 UTC, hyyan commented on src/main/java/com/webforj/samples/views/loadingbusy/LoadingDemoView.java
> +    guideIcon.setStyle("width", "100px");
use the `setSize` methods instead of setStyle

2024-10-10 08:57 UTC, hyyan commented on src/main/java/com/webforj/samples/views/loadingbusy/LoadingSpinnerDemoView.java
> +    interval = new Interval(3f, new EventListener<Interval.ElapsedEvent>() {
Make this anonymous inner class a lambda

2024-10-10 08:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/spinner/SpinnerDirectionDemoView.java
> +    .window {
use flexlayout component instead

2024-10-10 08:59 UTC, hyyan commented on src/main/java/com/webforj/samples/views/spinner/SpinnerExpanseDemoView.java
> +    .window {
use flexlayout component instead

2024-10-10 08:59 UTC, hyyan commented on src/main/java/com/webforj/samples/views/spinner/SpinnerSpeedDemoView.java
> +    .window {
use flexlayout component instead

2024-10-10 08:59 UTC, hyyan commented on src/main/java/com/webforj/samples/views/spinner/SpinnerThemeDemoView.java
> +    .window {
use flexlayout component instead

2024-10-10 09:01 UTC, hyyan commented
Looks great overall, @laurenic0l. I've requested some code style and cleanup changes.

2024-10-10 09:27 UTC, hyyan commented on src/main/java/com/webforj/samples/views/loadingbusy/BusyDemoView.java
> +public class BusyDemoView extends Composite<Div> {
Can we make the form a bit wider please.

2024-10-11 21:12 UTC, laurenic0l commented
@hyyan finished applying changes. The `SpinnerDemoView` is being used at the beginning of the `Spinner` article.

2024-10-14 11:05 UTC, hyyan commented
@laurenic0l, I still notice many of the issues haven't been resolved. Could you please double-check them? Also, take a look at [Eric's PR](https://github.com/webforj/webforj-docs-samples/pull/86) for an example of the best practices we're aiming for.

2024-10-14 12:29 UTC, hyyan commented on src/main/java/com/webforj/samples/views/loadingbusy/LoadingDemoView.java
> +    guideIcon.setStyle("width", "100px");
@laurenic0l could you please open an issue for that

2024-10-15 10:11 UTC, MatthewHawkins approved these changes
Looks good, I particularly like the LoadingDemo you created, nice work!

2024-10-16 09:18 UTC, hyyan commented on src/main/resources/css/loadingstyles/loadingdemo.css
> +.window {
is this still needed ?

2024-10-16 09:19 UTC, hyyan commented on src/main/resources/css/spinnerstyles/spinnerdirectiondemo.css
> +.window {
is this still needed ?

2024-10-16 13:50 UTC, laurenic0l commented on src/main/resources/css/loadingstyles/loadingdemo.css
> +.window {
removed

2024-10-16 13:50 UTC, laurenic0l commented on src/main/resources/css/spinnerstyles/spinnerdirectiondemo.css
> +.window {
removed

2024-10-17 10:27 UTC, merged