PR - Toast Demos
webforj/webforj-docs-samples pull request #87
Opened 2024-10-17 15:43 UTC by laurenic0l

Updated the toast demos to reflect the routing changes.

2024-10-17 15:46 UTC, MatthewHawkins submitted a review, later dismissed

2024-10-23 11:05 UTC, MatthewHawkins commented
@hyyan I just ran these and tested - they look good for me and are ready for your review

2024-10-23 11:11 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastCookiesDemoView.java
> +    acceptButton.addClassName("acceptbutton");
Use the primary theme for accept button

2024-10-23 11:58 UTC, hyyan requested changes

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastCookiesDemoView.java
> +    buttonContainer = new Div();
Use FlexLayout and remove the css part

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastCookiesDemoView.java
> +    cookieIcon = TablerIcon.create("cookie");
Use the Default theme. The current gray theme with custom content doesn't look visually appealing enough.

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastCookiesDemoView.java
> +    necessaryButton.addClassName("necessarybutton");
use the ButtonTheme.OUTLINED_PRIMARY theme please

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastCookiesDemoView.java
> +  Button customizeButton;
Let's get of the customize button please

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastCookiesDemoView.java
> +@InlineStyleSheet("context://css/toaststyles/toastcookiesdemo.css")
rename the folder to just `toast` please

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastPlacementDemoView.java
> +    List<ListItem> placementOptions = new ArrayList<>();
We need to aim to simplify the code as mush as possible, rewriting this one like this would be a bit better:

```java
List<ListItem> placementOptions = new ArrayList<>();
    placementOptions.add(new ListItem(Placement.TOP, "TOP"));
    placementOptions.add(new ListItem(Placement.TOP_LEFT, "TOP_LEFT"));
    placementOptions.add(new ListItem(Placement.TOP_RIGHT, "TOP_RIGHT"));
    placementOptions.add(new ListItem(Placement.CENTER, "CENTER"));
    placementOptions.add(new ListItem(Placement.BOTTOM, "BOTTOM"));
    placementOptions.add(new ListItem(Placement.BOTTOM_LEFT, "BOTTOM_LEFT"));
    placementOptions.add(new ListItem(Placement.BOTTOM_RIGHT, "BOTTOM_RIGHT"));

    placementChoiceBox.insert(placementOptions);
    placementChoiceBox.selectIndex(4);
    placementChoiceBox.setMinWidth(160);

    showToastButton = new Button("Show Toast", ButtonTheme.PRIMARY, e -> {
      Placement selectedPlacement = Placement.valueOf(placementChoiceBox.getText());
      Toast.show("This is a toast notification", selectedPlacement);
    });
```

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastInteractiveDemoView.java
> +public class ToastInteractiveDemoView extends Composite<Div> {
This one is not needed anymore

2024-10-23 11:58 UTC, hyyan commented on src/main/java/com/webforj/samples/views/toast/ToastThemeDemoView.java
> +    laterButton = new Button("Later");
Remove the buttons please

2024-10-23 11:59 UTC, hyyan commented
@laurenic0l looks great overall. I requested few changes

2024-10-24 10:27 UTC, hyyan approved these changes

2024-10-24 10:30 UTC, hyyan commented
@MatthewHawkins, this and the docs PR look good after a bit of housekeeping. The CSS file name should be in CamelCase like the others for consistency. Could you please update both this PR and the docs PR to reflect that? or @laurenic0l can do it, and then you can merge.

2024-10-24 12:29 UTC, laurenic0l commented
@hyyan @MatthewHawkins done! Ready to go.

2024-10-24 13:11 UTC, MatthewHawkins approved these changes

2024-10-24 13:12 UTC, merged