PR - Text Field Demo
webforj/webforj-docs-samples pull request #95
Opened 2024-10-25 15:38 UTC by laurenic0l

closes #80

2024-10-28 08:49 UTC, MatthewHawkins requested changes
Looks good, but the text fields are cut off when the screen size shrinks - might just need to enable flex wrap!

2024-10-28 10:14 UTC, hyyan requested changes

2024-10-28 10:14 UTC, hyyan commented on src/main/java/com/webforj/samples/views/fields/textfield/TextFieldView.java
> +public class TextFieldView extends Composite<FlexLayout> {
- Add lables to the fiedls
- Make sure the demo is responsive

2024-10-31 13:10 UTC, MatthewHawkins approved these changes

2024-10-31 13:10 UTC, merged